import { EntitySchema } from "../../lib/entity/types";

const entityFields: EntitySchema = {
  tasks: {
    system: true,
    journal: true,
    workflow: true,
    permissions: {
      get: {
        default: false,
        rules: [
          {
            type: "field",
            filter: {
              createdby: "$user",
            },
          },
          {
            type: "role",
            roles: ["linkinq.admin"],
            filter: {},
          },
        ],
      },
    },
    fields: {
      refid: {
        seqformat: "TSK{id}07d",
        type: "text",
        label: "Refid",
        description: "System ID (autogenerated)",
      },
      description: {
        type: "richtext",
        label: "Description",
        description: "Description",
      },
      attn: {
        type: "nlink(users)",
        label: "Attn",
        description: "Attn",
      },
      assignee: {
        type: "link(users)",
        label: "Assignee",
        description: "Assignee",
      },
      attachments: {
        type: "nlink(attachments)",
        label: "Attachments",
        description: "Attachments",
      },
    },
  },
};

export default entityFields;
